### PR TITLE
fix(search): fix regression in get temporal entity evolution closes #229

### LINKED ISSUE #229: search service: regression in get temporal evolution only one attribute evolution is returned
regression introduced during handler migration to coroutines

### PR DESCRIPTION
**Pull request by philippestoltz**

### CODE REVIEW

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt [hunk 1]
```diff
@@ -95,20 +94,27 @@ class TemporalEntityHandler(
...
-        val temporalEntityAttribute = temporalEntityAttributeService.getForEntity(
+        val temporalEntityAttributes = temporalEntityAttributeService.getForEntity(
             entityId.toUri(),
             temporalQuery.attrs,
             contextLink
-        ).awaitFirstOrNull() ?: throw ResourceNotFoundException(entityNotFoundMessage(entityId))
+        ).collectList().awaitFirst()
 
-        val results = attributeInstanceService.search(temporalQuery, temporalEntityAttribute).awaitFirst()
+        if (temporalEntityAttributes.isEmpty()) throw ResourceNotFoundException(entityNotFoundMessage(entityId))
```
Comment (HoucemKacem) [inline search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:103]: Can you try this ?
`.collectList().awaitFirst().ifEmpty {throw ResourceNotFoundException(entityNotFoundMessage(entityId))}`

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt [hunk 2]
```diff
@@ -95,20 +94,27 @@ class TemporalEntityHandler(
...
 
-        val jsonLdEntity = loadEntityPayload(temporalEntityAttribute, bearerToken).awaitFirst()
+        val attributeAndResultsMap = temporalEntityAttributes.map { attribute ->
```
Comment (HoucemKacem) [inline search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:105]: temporalEntityAttribute ->

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt [hunk 3]
```diff
@@ -95,20 +94,27 @@ class TemporalEntityHandler(
...
+            val results = attributeInstanceService.search(temporalQuery, attribute).awaitFirst()
```
Comment (HoucemKacem) [inline search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:106]: Maybe you can avoid declaring results

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt [hunk 4]
```diff
@@ -95,20 +94,27 @@ class TemporalEntityHandler(
...
+            attribute to results
+        }.toMap()
+
+        val jsonLdEntity = loadEntityPayload(attributeAndResultsMap.keys.first(), bearerToken).awaitFirst()
+        val listOfResults = attributeAndResultsMap.values.toList()
```
Comment (HoucemKacem) [inline search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:111]: Maybe you can avoid declaring listOfResults

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt (hunk 1 above)
Comment (philippestoltz) [reply search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:103]: Yes, didn't know that one, it's handy

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt (hunk 2 above)
Comment (philippestoltz) [reply search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:105]: I thought it was too long name, I'm going to use "it"  if you don't mind

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt (hunk 3 above)
Comment (philippestoltz) [reply search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:106]: ok , I will then it replace by " it to attributeInstanceService.search(temporalQuery, attribute).awaitFirst()"

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt (hunk 4 above)
Comment (philippestoltz) [reply search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:111]: ok

**Review by HoucemKacem — APPROVED** [review]

File: search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt [hunk 5]
```diff
@@ -371,26 +372,45 @@ class TemporalEntityHandlerTests {
 
     @Test
     fun `it should return a single entity if the entity has two temporal properties`() {
-        val entityTemporalProperty1 = TemporalEntityAttribute(
```
Comment (bobeal) [inline search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt:374]: I've the feeling that this test is getting big and multi-purpose, isn't it?

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt [hunk 6]
```diff
@@ -95,20 +94,23 @@ class TemporalEntityHandler(
...
+        val attributeAndResultsMap = temporalEntityAttributes.map {
+            it to attributeInstanceService.search(temporalQuery, it).awaitFirst()
+        }.toMap()
 
-        val jsonLdEntity = loadEntityPayload(temporalEntityAttribute, bearerToken).awaitFirst()
+        val jsonLdEntity = loadEntityPayload(attributeAndResultsMap.keys.first(), bearerToken).awaitFirst()
         val jsonLdEntityWithTemporalValues = temporalEntityAttributeService.injectTemporalValues(
             jsonLdEntity,
-            listOf(results),
+            attributeAndResultsMap.values.toList(),
```
Comment (bobeal) [inline search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:110]: it could have been improved by taking rid of some of the Reactor legacy but it seems to work as expected

File: search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt (hunk 5 above)
Comment (philippestoltz) [reply search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt:374]: In fact I didn't get much the purpose of this test, I can leave it untouched and create another one if it 's ok

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt (hunk 6 above)
Comment (philippestoltz) [reply search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:110]: You 're talking about loadEntityPayload() ? Last time I tried I got some timeouts. I'm not mastering reactor yet

File: search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt (hunk 5 above)
Comment (bobeal) [reply search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt]: Indeed, I think it is a kind of legacy test that lost most of its purpose...

File: search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt (hunk 6 above)
Comment (bobeal) [reply search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt:110]: No, I'm talking about the whole selected block that reflects some past workarounds due to Reactor constraints that could be removed now. Let's talk about it tomorrow.
